# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodypage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloger',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
