# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodypage', '0002_bloger_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloger',
            name='likelist',
            field=models.ManyToManyField(blank=True, null=True, to='bodypage.Bloger', verbose_name='关注列表'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, verbose_name='标题'),
        ),
    ]
