# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodypage', '0003_auto_20161110_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloger',
            name='signiture',
            field=models.CharField(max_length=100),
        ),
    ]
