# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodypage', '0004_auto_20161110_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloger',
            name='likelist',
            field=models.ManyToManyField(blank=True, null=True, related_name='re_likelists', to='bodypage.Bloger', verbose_name='关注列表'),
        ),
    ]
