# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodypage', '0009_auto_20161118_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloger',
            name='portrait',
            field=models.ImageField(default='/media/pic/timg.jpg', upload_to='/media/pic/', verbose_name='头像'),
        ),
    ]
