# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodypage', '0010_auto_20161124_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloger',
            name='portrait',
            field=models.ImageField(default='pic/timg.jpg', upload_to='pic', verbose_name='头像'),
        ),
    ]
